-- ============================================================
-- GAMING NATION — complete database setup
--
-- Run this ONCE in Supabase → SQL Editor. It is idempotent: safe
-- on a fresh project and safe to re-run over the existing one.
-- Nothing here drops data.
--
-- After this runs, the platform works. Everything in it was
-- verified against the live project rather than assumed — the
-- column types below are the ones actually there.
--
--   auth.users.id  (uuid)
--         |
--         v
--   drivers.auth_user_id (uuid)
--   drivers.id           (bigint)  <-- applications.reviewed_by
--   drivers.driver_code  (text)    <-- applications.driver_id
--
-- Note the two different keys. drivers.id is a bigint identity,
-- NOT a uuid; the only uuid on a driver is auth_user_id. And
-- applications.driver_id is text, holding the HLL driver code.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Tables
-- ------------------------------------------------------------

create table if not exists public.drivers (
  id            bigint generated by default as identity primary key,
  driver_code   text,
  auth_user_id  uuid references auth.users(id) on delete set null,
  full_name     text,
  email         text,
  country       text,
  role          text default 'driver',
  status        text default 'pending',
  created_at    timestamptz not null default now()
);

create table if not exists public.applications (
  id           bigint generated by default as identity primary key,
  driver_id    text,
  full_name    text,
  email        text,
  country      text,
  status       text default 'pending',
  reviewed_by  bigint,
  reviewed_at  timestamptz,
  created_at   timestamptz not null default now()
);

create table if not exists public.company (
  id          bigint primary key,
  version     bigint not null default 0,
  data        jsonb  not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);


-- ------------------------------------------------------------
-- 2. Columns the client writes that an older project may lack
--    (add column if not exists never destroys an existing one)
-- ------------------------------------------------------------

alter table public.drivers      add column if not exists country     text;
alter table public.drivers      add column if not exists role        text default 'driver';
alter table public.drivers      add column if not exists status      text default 'pending';
alter table public.applications add column if not exists driver_id   text;
alter table public.applications add column if not exists reviewed_by bigint;
alter table public.applications add column if not exists reviewed_at timestamptz;


-- ------------------------------------------------------------
-- 3. Keys and indexes
--
-- driver_code must be unique: Accounts.register() generates it
-- randomly (HLL + four digits) and nothing else stops a clash.
-- ------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'drivers_driver_code_key') then
    alter table public.drivers add constraint drivers_driver_code_key unique (driver_code);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'drivers_auth_user_id_key') then
    alter table public.drivers add constraint drivers_auth_user_id_key unique (auth_user_id);
  end if;

  -- applications.reviewed_by names the recruiter handling it
  if not exists (select 1 from pg_constraint where conname = 'applications_reviewed_by_fkey') then
    alter table public.applications
      add constraint applications_reviewed_by_fkey
      foreign key (reviewed_by) references public.drivers(id) on delete set null;
  end if;
end $$;

create index if not exists applications_driver_id_idx on public.applications (driver_id);
create index if not exists applications_status_idx    on public.applications (status);
create index if not exists drivers_auth_user_id_idx   on public.drivers (auth_user_id);


-- ------------------------------------------------------------
-- 4. company.version must move, or nothing notices a change
--
-- Sync.pull() compares data.version against what it holds and
-- only reports a change when it differs. Sync.sendNow() upserts
-- id/data and never touches version — so without this trigger
-- the version stays 0 for ever, and a change written on one
-- machine never registers as new on another.
-- ------------------------------------------------------------

create or replace function public.company_touch()
returns trigger
language plpgsql
as $$
begin
  new.version    := coalesce(old.version, 0) + 1;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists company_touch on public.company;
create trigger company_touch
  before update on public.company
  for each row execute function public.company_touch();


-- ------------------------------------------------------------
-- 5. The company row Sync.pull() looks for
-- ------------------------------------------------------------

insert into public.company (id, version, data)
values (1, 0, '{}'::jsonb)
on conflict (id) do nothing;


-- ============================================================
-- 6. Row level security
--
-- A helper first, so every staff policy says the same thing in
-- one place. SECURITY DEFINER matters: a policy on drivers that
-- selects from drivers would otherwise recurse.
-- ============================================================

create or replace function public.is_staff()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.drivers
    where auth_user_id = auth.uid()
      and role in ('recruiter', 'management', 'admin', 'super_admin')
  );
$$;

grant execute on function public.is_staff() to authenticated;

alter table public.drivers      enable row level security;
alter table public.applications enable row level security;
alter table public.company      enable row level security;


-- ---- drivers ----

drop policy if exists "Drivers can insert their own profile" on public.drivers;
create policy "Drivers can insert their own profile"
on public.drivers for insert to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "Drivers can read their own profile" on public.drivers;
create policy "Drivers can read their own profile"
on public.drivers for select to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "Drivers can update their own profile" on public.drivers;
create policy "Drivers can update their own profile"
on public.drivers for update to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

-- Staff see the whole roster; without this a recruiter sees only
-- themselves and every fleet screen comes up empty.
drop policy if exists "Staff can read every driver" on public.drivers;
create policy "Staff can read every driver"
on public.drivers for select to authenticated
using (public.is_staff());

drop policy if exists "Staff can manage drivers" on public.drivers;
create policy "Staff can manage drivers"
on public.drivers for update to authenticated
using (public.is_staff())
with check (public.is_staff());


-- ---- applications ----

-- Someone may file their own application: the driver code on it
-- has to be one of theirs, not somebody else's.
drop policy if exists "Drivers can file their own application" on public.applications;
create policy "Drivers can file their own application"
on public.applications for insert to authenticated
with check (
  driver_id in (select driver_code from public.drivers where auth_user_id = auth.uid())
);

drop policy if exists "Drivers can read their own applications" on public.applications;
create policy "Drivers can read their own applications"
on public.applications for select to authenticated
using (
  driver_id in (select driver_code from public.drivers where auth_user_id = auth.uid())
);

drop policy if exists "Staff can read every application" on public.applications;
create policy "Staff can read every application"
on public.applications for select to authenticated
using (public.is_staff());

-- Deciding an application is a staff act. Deliberately NOT open
-- to every authenticated user: an applicant could otherwise
-- approve themselves and release the client download to
-- themselves.
drop policy if exists "Staff can decide applications" on public.applications;
create policy "Staff can decide applications"
on public.applications for update to authenticated
using (public.is_staff())
with check (public.is_staff());


-- ---- company ----
-- One row, id = 1, holding the shared record. Everybody signed
-- in reads it and everybody signed in writes it, because any
-- driver's own change has to reach it.

drop policy if exists "Signed-in users can read the company" on public.company;
create policy "Signed-in users can read the company"
on public.company for select to authenticated
using (true);

drop policy if exists "Signed-in users can create the company" on public.company;
create policy "Signed-in users can create the company"
on public.company for insert to authenticated
with check (true);

drop policy if exists "Signed-in users can update the company" on public.company;
create policy "Signed-in users can update the company"
on public.company for update to authenticated
using (true) with check (true);


-- ============================================================
-- 7. Backfill for a project that already has rows
-- ============================================================

-- applications filed before driver_id existed, matched on the
-- only thing both rows carry: the email address
update public.applications as a
set driver_id = d.driver_code
from public.drivers as d
where a.driver_id is null
  and lower(a.email) = lower(d.email);

-- a driver with no role cannot pass any staff check
update public.drivers set role   = 'driver' where role   is null;
update public.drivers set status = 'active' where status is null;


-- ============================================================
-- 8. Check it worked
--
-- Run these after the script. The first should list your drivers
-- with an auth_user_id on each; the second should return true
-- when you are signed in as staff.
-- ============================================================

-- select id, driver_code, auth_user_id, full_name, email, role, status
--   from public.drivers order by id;

-- select id, driver_id, full_name, email, country, status, reviewed_by
--   from public.applications order by id desc;

-- select public.is_staff();
