/* ============================================================
   Lets the Android app reach the telemetry server on your LAN.

     node tools/android-network.js     (run automatically by npm run android)

   Two separate things block it out of the box:

   1. The WebView is served from https://localhost (Capacitor's default
      androidScheme), so fetching http://192.168.x.x:25555 is mixed
      content and is blocked. Fixed by allowMixedContent in
      capacitor.config.json.

   2. Since Android 9, cleartext HTTP is refused unless the app opts in.
      Fixed by the network security config written below.

   The telemetry server is a plain HTTP service on the driver's own
   network and its address is whatever the user types, so it cannot be
   pinned to a known domain. Cleartext is therefore allowed generally —
   the trade-off every telemetry companion app makes. Nothing sensitive
   travels over it: it is truck position and speed on your own LAN.

   Idempotent, so it is safe to re-run and it survives deleting android/.
   ============================================================ */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MAIN = path.join(ROOT, 'android', 'app', 'src', 'main');
if (!fs.existsSync(MAIN)) {
  console.log('  (no android project yet — skipping network config)');
  process.exit(0);
}

/* ---- 1. network security config ---- */
const xmlDir = path.join(MAIN, 'res', 'xml');
fs.mkdirSync(xmlDir, { recursive: true });
const nscPath = path.join(xmlDir, 'network_security_config.xml');
const nsc = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/android-network.js -->
<network-security-config>
    <!-- The telemetry server is plain HTTP on the driver's own network and
         its address is user-configurable, so it cannot be pinned here. -->
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;
let wrote = 0;
if (!fs.existsSync(nscPath) || fs.readFileSync(nscPath, 'utf8') !== nsc) {
  fs.writeFileSync(nscPath, nsc);
  wrote++;
  console.log('  wrote res/xml/network_security_config.xml');
}

/* ---- 2. point the manifest at it ---- */
const manifestPath = path.join(MAIN, 'AndroidManifest.xml');
let m = fs.readFileSync(manifestPath, 'utf8');
const before = m;

if (!/android:networkSecurityConfig/.test(m)) {
  m = m.replace(
    /(<application\b)/,
    '$1\n        android:networkSecurityConfig="@xml/network_security_config"'
  );
}
if (!/android:usesCleartextTraffic/.test(m)) {
  m = m.replace(
    /(<application\b)/,
    '$1\n        android:usesCleartextTraffic="true"'
  );
}
/* the client polls a server on the network */
if (!/android\.permission\.INTERNET/.test(m)) {
  m = m.replace('</manifest>',
    '\n    <uses-permission android:name="android.permission.INTERNET" />\n</manifest>');
}
if (!/ACCESS_NETWORK_STATE/.test(m)) {
  m = m.replace('</manifest>',
    '    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />\n</manifest>');
}

if (m !== before) {
  fs.writeFileSync(manifestPath, m);
  wrote++;
  console.log('  patched AndroidManifest.xml (cleartext + network permissions)');
}

/* ---- 3. mixed content must be on, or the https page cannot call http ---- */
const capPath = path.join(ROOT, 'capacitor.config.json');
if (fs.existsSync(capPath)) {
  const cap = JSON.parse(fs.readFileSync(capPath, 'utf8'));
  cap.android = cap.android || {};
  if (cap.android.allowMixedContent !== true) {
    cap.android.allowMixedContent = true;
    fs.writeFileSync(capPath, JSON.stringify(cap, null, 2) + '\n');
    wrote++;
    console.log('  enabled allowMixedContent in capacitor.config.json');
  }
}

console.log(wrote ? '  network config updated' : '  network config already correct');
