-- ============================================================
-- GAMING NATION — driver to driver messaging
--
-- Run this in Supabase -> SQL Editor. Idempotent, like the rest of
-- supabase/: safe on a fresh project, safe to re-run, and it drops
-- nothing.
--
-- WHY THIS FILE EXISTS
--
-- Messages were the last thing on the platform still talking to
-- fleet-server.js. Everything else moved to Supabase, so a driver
-- who opened Messages on the website was told
--
--   "Messages need the company service. Start it with npm run
--    service, or set its address in Settings."
--
-- which is a true sentence about a service nobody outside the
-- office runs. The conversation could not leave one machine.
--
-- WHAT WAS ALREADY THERE
--
-- The live project (sfzeauvkguywidrqjntk) was read on 2026-09-08
-- and already had, by hand:
--
--   conversations               (id bigint, created_at, updated_at)
--   conversation_participants   (conversation_id bigint, driver_id uuid, joined_at)
--   conversation_members        (conversation_id bigint, user_id uuid, joined_at)
--   messages                    (id bigint, conversation_id bigint,
--                                sender_id uuid, message text,
--                                read_at, created_at)
--
-- Note conversation_participants.driver_id is a **uuid**, not a
-- driver code and not drivers.id. It is auth.users.id. The name
-- says driver and the type says auth user; this file goes with the
-- type, because that is what the rows actually hold.
--
-- conversation_members is the same table under a second name —
-- two passes at the same idea. This file treats
-- conversation_participants as the real one, copies anything in
-- conversation_members across, and leaves that table alone.
-- Dropping a table with rows in it is not something a migration
-- should decide on its own.
--
-- WHAT WAS MISSING, AND WHY EACH ONE IS SILENT
--
--   * No row level security policies. With RLS on and no policy,
--     every select is a SUCCESSFUL query returning zero rows —
--     indistinguishable from "nobody has messaged you".
--   * Not in the supabase_realtime publication. A subscription
--     reports SUBSCRIBED and then stays quiet for ever.
--   * No way for the browser to open a conversation. Creating one
--     means inserting a participant row for the OTHER person,
--     which no honest policy can allow. That is what the
--     SECURITY DEFINER functions below are for.
--
-- THE SHAPE THE CLIENT TALKS IN
--
-- script.js is keyed on the GMN driver code ("GMN001") in 213
-- places. The tables are keyed on auth uuids. Rather than teach
-- the browser to translate — which it cannot do anyway, because a
-- plain driver may only read their own drivers row — every
-- function here takes and returns driver codes and does the
-- translation in the database.
-- ============================================================


-- ------------------------------------------------------------
-- 0. The driver photo column, repeated from 20260907_driver_avatar.sql
--
-- Not a copy-paste slip. The live project was checked on
-- 2026-09-08 and drivers.avatar was NOT there, so that migration
-- has not been run — which is the whole of the "my profile
-- picture disappears when I reload" report. persistAvatar()
-- writes it, the write is refused for a column that does not
-- exist, the failure is caught and logged, and the photo survives
-- only as long as the local record does.
--
-- add column if not exists does nothing when it is already there,
-- so running both files in either order is fine.
-- ------------------------------------------------------------

alter table public.drivers add column if not exists avatar text;


-- ------------------------------------------------------------
-- 1. The tables, reconciled rather than assumed
-- ------------------------------------------------------------

create table if not exists public.conversations (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 'dm' is a conversation between two drivers; 'room' is one
-- everybody in the company is in. The fleet room is drawn by
-- messagesPanes() and has always come from the company service —
-- without a kind here it would be the one thing left behind.
alter table public.conversations add column if not exists kind text not null default 'dm';

-- Only rooms carry one. It is what makes "the fleet room" a single
-- row rather than a new one per person who opens it.
alter table public.conversations add column if not exists slug text;

-- Not a partial index, deliberately. A unique index in Postgres already
-- lets any number of rows hold NULL, so "unique when set" needs no
-- predicate — and a predicate here would have to be repeated in every
-- ON CONFLICT (slug) below, because inference against a partial index
-- only matches when the statement restates it.
create unique index if not exists conversations_slug_key
  on public.conversations (slug);

-- Ordering the thread list by "most recent first" is the only way
-- anyone reads it, and updated_at is what that means.
create index if not exists conversations_updated_idx
  on public.conversations (updated_at desc);


create table if not exists public.conversation_participants (
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  driver_id       uuid   not null references auth.users(id) on delete cascade,
  joined_at       timestamptz not null default now()
);

-- Read receipts per person, not per message.
--
-- messages.read_at is one column shared by everybody who can see
-- the message, which works for a two-person conversation and is
-- wrong the moment a room has three people in it. This is the
-- honest version: the last moment THIS driver looked. Unread is
-- then "messages newer than that", which is also how the badge in
-- the sidebar is counted.
alter table public.conversation_participants
  add column if not exists last_read_at timestamptz not null default 'epoch';

-- One row per person per conversation.
--
-- Without this, dm_with() files a second membership every time somebody
-- opens a thread, and every ON CONFLICT below has nothing to infer
-- against — which is not a warning, it is an error at the point of use.
--
-- A unique INDEX rather than only a primary key, and the two are not
-- interchangeable here. ON CONFLICT infers from a unique index, so the
-- index is what the functions actually need; the primary key is added
-- as well when the table has none, because a table already carrying one
-- under a different name cannot be given a second.
do $$
begin
  delete from public.conversation_participants a
  using public.conversation_participants b
  where a.ctid > b.ctid
    and a.conversation_id = b.conversation_id
    and a.driver_id = b.driver_id;
end $$;

create unique index if not exists conversation_participants_uniq
  on public.conversation_participants (conversation_id, driver_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.conversation_participants'::regclass
      and contype = 'p'
  ) then
    alter table public.conversation_participants
      add constraint conversation_participants_pkey
      primary key (conversation_id, driver_id);
  end if;
end $$;

create index if not exists conversation_participants_driver_idx
  on public.conversation_participants (driver_id);


create table if not exists public.messages (
  id              bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id       uuid   not null references auth.users(id) on delete cascade,
  message         text,
  read_at         timestamptz,
  created_at      timestamptz not null default now()
);

-- A photo or a file, as {id, name, size, type, image, path}. The
-- bytes live in the 'dm' storage bucket set up in section 7; this
-- is the record of what is there, so a message can be listed
-- without fetching it.
alter table public.messages add column if not exists attachment jsonb;

-- Removing a message keeps the row and blanks it, so the other end
-- sees "message removed" where it was rather than the conversation
-- silently reflowing around a hole.
alter table public.messages add column if not exists deleted_at timestamptz;

-- The one query the conversation view makes, every time.
create index if not exists messages_conversation_idx
  on public.messages (conversation_id, id desc);

create index if not exists messages_sender_idx
  on public.messages (sender_id);


-- The second name for conversation_participants. Anything filed
-- there is brought across; the table itself is left where it is.
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'conversation_members'
  ) then
    insert into public.conversation_participants (conversation_id, driver_id)
    select m.conversation_id, m.user_id
    from public.conversation_members m
    where m.conversation_id is not null
      and m.user_id is not null
      and exists (select 1 from public.conversations c where c.id = m.conversation_id)
      and exists (select 1 from auth.users u where u.id = m.user_id)
    on conflict (conversation_id, driver_id) do nothing;
  end if;
end $$;


-- ------------------------------------------------------------
-- 2. A conversation's clock
--
-- The thread list is ordered by conversations.updated_at, so a
-- conversation that is not touched when a message lands in it
-- sinks to the bottom of the list the moment it becomes the most
-- interesting one there.
-- ------------------------------------------------------------

create or replace function public.messages_touch_conversation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.conversations
     set updated_at = now()
   where id = new.conversation_id;
  return new;
end $$;

drop trigger if exists messages_touch_conversation on public.messages;
create trigger messages_touch_conversation
  after insert on public.messages
  for each row execute function public.messages_touch_conversation();


-- ------------------------------------------------------------
-- 3. Translating between what the app says and what the tables hold
--
-- SECURITY DEFINER on all three: a plain driver may only read
-- their own drivers row, so resolving anybody else's code is
-- something only the database can do. They give out a driver code
-- and a name — what a messages screen already shows — and nothing
-- else off the row.
-- ------------------------------------------------------------

create or replace function public.dm_uid(code text)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select auth_user_id
  from public.drivers
  where driver_code = code
    and auth_user_id is not null
  limit 1;
$$;

create or replace function public.dm_code(who uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select driver_code
  from public.drivers
  where auth_user_id = who
  limit 1;
$$;

create or replace function public.dm_is_member(conversation bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.conversation_participants
    where conversation_id = conversation
      and driver_id = auth.uid()
  ) or exists (
    -- everybody in the company is in the room, whether or not they
    -- have opened it yet
    select 1 from public.conversations
    where id = conversation and kind = 'room'
  );
$$;

grant execute on function public.dm_uid(text)      to authenticated;
grant execute on function public.dm_code(uuid)     to authenticated;
grant execute on function public.dm_is_member(bigint) to authenticated;


-- ------------------------------------------------------------
-- 4. Row level security
--
-- These policies are what make the realtime subscription work as
-- much as they are what protects the rows: postgres_changes
-- re-checks the SELECT policy for the subscribing user before it
-- forwards a row, so a table with RLS on and no read policy is a
-- subscription that never fires.
-- ------------------------------------------------------------

alter table public.conversations             enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages                  enable row level security;


-- ---- conversations ----

drop policy if exists "Members read their conversations" on public.conversations;
create policy "Members read their conversations"
on public.conversations for select to authenticated
using (kind = 'room' or public.dm_is_member(id));

-- Creating one goes through dm_with() / dm_room(), which are
-- SECURITY DEFINER. Deliberately no insert policy: a conversation
-- created directly by the browser would have no participants and
-- nobody could ever see it.


-- ---- conversation_participants ----

drop policy if exists "Members read the membership" on public.conversation_participants;
create policy "Members read the membership"
on public.conversation_participants for select to authenticated
using (driver_id = auth.uid() or public.dm_is_member(conversation_id));

-- Updating your own last_read_at is how "read" is recorded, and it
-- is the one write on this table the browser makes directly.
drop policy if exists "Drivers mark their own reading" on public.conversation_participants;
create policy "Drivers mark their own reading"
on public.conversation_participants for update to authenticated
using (driver_id = auth.uid())
with check (driver_id = auth.uid());


-- ---- messages ----

drop policy if exists "Members read the conversation" on public.messages;
create policy "Members read the conversation"
on public.messages for select to authenticated
using (public.dm_is_member(conversation_id));

-- sender_id = auth.uid() is the whole of it: who sent a message is
-- decided from the session, never believed from the body. Without
-- this line anybody could post as anybody.
drop policy if exists "Members write to the conversation" on public.messages;
create policy "Members write to the conversation"
on public.messages for insert to authenticated
with check (sender_id = auth.uid() and public.dm_is_member(conversation_id));

drop policy if exists "Senders can remove their own message" on public.messages;
create policy "Senders can remove their own message"
on public.messages for update to authenticated
using (sender_id = auth.uid())
with check (sender_id = auth.uid());


-- ------------------------------------------------------------
-- 5. What the browser actually calls
--
-- Every one of these takes and returns driver codes. The browser
-- never sees a uuid and never has to resolve one.
-- ------------------------------------------------------------

-- The conversation with one other driver, created if this is the
-- first thing either of them has said.
--
-- The two participant rows are the reason this is a function.
-- Opening a conversation means filing a membership for somebody
-- else, and no policy on conversation_participants can allow that
-- without also letting anyone add themselves to any conversation
-- they like.
create or replace function public.dm_with(other_code text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me    uuid := auth.uid();
  other uuid := public.dm_uid(other_code);
  found bigint;
begin
  if me is null then
    raise exception 'not signed in';
  end if;

  if other is null then
    raise exception 'no driver with the code %', other_code;
  end if;

  if other = me then
    raise exception 'that is your own driver code';
  end if;

  -- The existing one: a 'dm' both of them are in. Counted rather
  -- than joined twice, so a conversation that somehow gained a
  -- third member is not mistaken for this pair's.
  select c.id into found
  from public.conversations c
  where c.kind = 'dm'
    and (select count(*) from public.conversation_participants p
          where p.conversation_id = c.id) = 2
    and exists (select 1 from public.conversation_participants p
                 where p.conversation_id = c.id and p.driver_id = me)
    and exists (select 1 from public.conversation_participants p
                 where p.conversation_id = c.id and p.driver_id = other)
  order by c.id
  limit 1;

  if found is not null then
    return found;
  end if;

  insert into public.conversations (kind) values ('dm') returning id into found;

  insert into public.conversation_participants (conversation_id, driver_id)
  values (found, me), (found, other)
  on conflict (conversation_id, driver_id) do nothing;

  return found;
end $$;


-- The one room the whole company is in.
create or replace function public.dm_room()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me    uuid := auth.uid();
  found bigint;
begin
  if me is null then
    raise exception 'not signed in';
  end if;

  select id into found from public.conversations where slug = '#fleet' limit 1;

  if found is null then
    insert into public.conversations (kind, slug) values ('room', '#fleet')
    on conflict (slug) do nothing
    returning id into found;

    -- somebody else created it between the select and the insert
    if found is null then
      select id into found from public.conversations where slug = '#fleet' limit 1;
    end if;
  end if;

  -- Membership in a room is only there to carry last_read_at.
  -- dm_is_member() lets everybody in regardless.
  --
  -- Joined as having read it, not as having read nothing. The column
  -- defaults to the epoch, which is right for a conversation somebody
  -- has been part of all along and wrong for a room they are walking
  -- into: every message the company has ever sent would land on them at
  -- once as unread, on their first load, for ever after.
  insert into public.conversation_participants (conversation_id, driver_id, last_read_at)
  values (found, me, now())
  on conflict (conversation_id, driver_id) do nothing;

  return found;
end $$;


-- The thread list: one row per conversation, newest first, with
-- the last thing said in it and how much of it is unread.
--
-- Assembled here rather than in the browser because the browser
-- would need four round trips and a second table it is not allowed
-- to read to build the same thing.
create or replace function public.dm_threads()
returns table (
  conversation_id bigint,
  kind            text,
  with_code       text,
  with_name       text,
  last_text       text,
  last_at         timestamptz,
  last_mine       boolean,
  last_deleted    boolean,
  unread          integer
)
language sql
stable
security definer
set search_path = public
as $$
  with mine as (
    select c.id, c.kind, c.updated_at, p.last_read_at
    from public.conversations c
    join public.conversation_participants p
      on p.conversation_id = c.id and p.driver_id = auth.uid()
  ),
  last_msg as (
    select distinct on (m.conversation_id)
           m.conversation_id, m.message, m.created_at, m.sender_id,
           m.deleted_at, m.attachment
    from public.messages m
    where m.conversation_id in (select id from mine)
    order by m.conversation_id, m.id desc
  )
  select
    mine.id,
    mine.kind,
    -- a room has no other person; a dm has exactly one
    case when mine.kind = 'room' then null
         else (select public.dm_code(p2.driver_id)
                 from public.conversation_participants p2
                where p2.conversation_id = mine.id
                  and p2.driver_id <> auth.uid()
                limit 1) end,
    case when mine.kind = 'room' then 'Fleet room'
         else (select d.full_name
                 from public.conversation_participants p2
                 join public.drivers d on d.auth_user_id = p2.driver_id
                where p2.conversation_id = mine.id
                  and p2.driver_id <> auth.uid()
                limit 1) end,
    case when last_msg.deleted_at is not null then null
         when last_msg.message is not null and last_msg.message <> '' then last_msg.message
         when last_msg.attachment is not null then null
         else null end,
    last_msg.created_at,
    last_msg.sender_id = auth.uid(),
    last_msg.deleted_at is not null,
    (select count(*)::int
       from public.messages m2
      where m2.conversation_id = mine.id
        and m2.sender_id <> auth.uid()
        and m2.deleted_at is null
        and m2.created_at > mine.last_read_at)
  from mine
  left join last_msg on last_msg.conversation_id = mine.id
  order by coalesce(last_msg.created_at, mine.updated_at) desc;
$$;


-- One conversation, oldest first, so the browser can print it top
-- to bottom without reversing it.
--
-- before_id pages backwards: pass the id of the oldest message on
-- screen to get the batch above it.
create or replace function public.dm_history(
  conversation bigint,
  before_id    bigint default null,
  limit_n      integer default 200
)
returns table (
  id           bigint,
  at           timestamptz,
  sender_code  text,
  sender_name  text,
  mine         boolean,
  body         text,
  attachment   jsonb,
  deleted      boolean,
  read_by_them boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select * from (
    select
      m.id,
      m.created_at,
      public.dm_code(m.sender_id),
      coalesce(d.full_name, 'Driver'),
      m.sender_id = auth.uid(),
      case when m.deleted_at is null then m.message else null end,
      case when m.deleted_at is null then m.attachment else null end,
      m.deleted_at is not null,
      -- "read" on a message I sent: has anybody else in the
      -- conversation looked since it landed
      exists (
        select 1 from public.conversation_participants p
        where p.conversation_id = m.conversation_id
          and p.driver_id <> auth.uid()
          and p.last_read_at >= m.created_at
      )
    from public.messages m
    left join public.drivers d on d.auth_user_id = m.sender_id
    where m.conversation_id = conversation
      and public.dm_is_member(conversation)
      and (before_id is null or m.id < before_id)
    order by m.id desc
    limit greatest(1, least(coalesce(limit_n, 200), 500))
  ) newest
  order by 1;
$$;


-- Sending. The conversation is resolved from the driver code, so
-- the first message to somebody opens the conversation on the way
-- through and the browser never has to ask for one separately.
create or replace function public.dm_send(
  other_code text,
  body       text default null,
  attach     jsonb default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me     uuid := auth.uid();
  target bigint;
  made   bigint;
begin
  if me is null then
    raise exception 'not signed in';
  end if;

  if (body is null or btrim(body) = '') and attach is null then
    raise exception 'nothing to send';
  end if;

  if other_code = '#fleet' then
    target := public.dm_room();
  else
    target := public.dm_with(other_code);
  end if;

  insert into public.messages (conversation_id, sender_id, message, attachment)
  values (target, me, nullif(btrim(coalesce(body, '')), ''), attach)
  returning id into made;

  -- Your own message is read by you the moment you send it, or the
  -- unread badge counts what you just typed.
  update public.conversation_participants
     set last_read_at = now()
   where conversation_id = target and driver_id = me;

  return made;
end $$;


create or replace function public.dm_mark_read(conversation bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return;
  end if;

  -- A room the driver has never opened has no membership row yet.
  insert into public.conversation_participants (conversation_id, driver_id, last_read_at)
  select conversation, auth.uid(), now()
  where public.dm_is_member(conversation)
  on conflict (conversation_id, driver_id)
  do update set last_read_at = now();
end $$;


-- Removing a message. Only your own, and it is blanked rather than
-- deleted so the other end sees that something was there.
create or replace function public.dm_delete(message_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  hit integer;
begin
  update public.messages
     set deleted_at = now(), message = null, attachment = null
   where id = message_id
     and sender_id = auth.uid()
     and deleted_at is null;

  get diagnostics hit = row_count;
  return hit > 0;
end $$;


-- Everybody a driver could talk to.
--
-- The roster the messages screen draws comes out of the company
-- record, which is fine on a machine that has pulled it and empty
-- on one that has not. This is the same list, from the table that
-- owns it, and it gives out only what the screen already shows.
create or replace function public.dm_directory()
returns table (code text, name text, role text)
language sql
stable
security definer
set search_path = public
as $$
  select d.driver_code, coalesce(d.full_name, 'Driver'), coalesce(d.role, 'driver')
  from public.drivers d
  where d.driver_code is not null
    and d.auth_user_id is not null
    and d.auth_user_id <> auth.uid()
    and coalesce(d.status, 'active') <> 'suspended'
    and auth.uid() is not null
  order by coalesce(d.full_name, 'Driver');
$$;


grant execute on function public.dm_with(text)                      to authenticated;
grant execute on function public.dm_room()                          to authenticated;
grant execute on function public.dm_threads()                       to authenticated;
grant execute on function public.dm_history(bigint, bigint, integer) to authenticated;
grant execute on function public.dm_send(text, text, jsonb)         to authenticated;
grant execute on function public.dm_mark_read(bigint)               to authenticated;
grant execute on function public.dm_delete(bigint)                  to authenticated;
grant execute on function public.dm_directory()                     to authenticated;


-- ------------------------------------------------------------
-- 6. Realtime
--
-- Without this the client polls and a message takes up to the
-- length of the poll to appear, which is the difference between a
-- conversation and a form. replica identity full so an UPDATE —
-- which is what removing a message is — carries the old row too.
-- ------------------------------------------------------------

alter table public.messages                  replica identity full;
alter table public.conversations             replica identity full;
alter table public.conversation_participants replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'conversation_participants'
  ) then
    alter publication supabase_realtime add table public.conversation_participants;
  end if;
end $$;


-- ------------------------------------------------------------
-- 7. Photos and files
--
-- A private bucket. The path is <conversation id>/<random>-<name>,
-- and the policies below resolve that first segment back to a
-- conversation and ask whether this driver is in it — so a signed
-- URL is issued only to somebody who can already read the message
-- the file is attached to.
--
-- storage.objects has RLS of its own; these are policies on that
-- table, not on the bucket row.
-- ------------------------------------------------------------

-- The conversation a storage path belongs to, or null if the name
-- is not shaped like one. A plain cast would raise on a path with
-- a non-numeric first segment and take the whole policy check down
-- with it.
create or replace function public.dm_path_conversation(object_name text)
returns bigint
language plpgsql
immutable
as $$
declare
  head text := split_part(coalesce(object_name, ''), '/', 1);
begin
  if head ~ '^\d+$' then
    return head::bigint;
  end if;
  return null;
end $$;

grant execute on function public.dm_path_conversation(text) to authenticated;

-- Wrapped, and this is the one place in this file that is.
--
-- storage.buckets and storage.objects are not ours; on some projects the
-- role running the SQL editor cannot write policies on them. The SQL
-- editor runs this whole file as one transaction, so an error here would
-- roll back the tables, the policies and the functions above it — and
-- the message on screen would be about storage, which is the least
-- important thing in the file.
--
-- So it is allowed to fail. Text messaging works without it; sending a
-- photo does not, and the client already says so in those words when the
-- bucket is missing.
do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit)
  values ('dm', 'dm', false, 26214400)
  on conflict (id) do nothing;

  drop policy if exists "Members read conversation files" on storage.objects;
  create policy "Members read conversation files"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'dm'
    and public.dm_is_member(public.dm_path_conversation(name))
  );

  drop policy if exists "Members attach files" on storage.objects;
  create policy "Members attach files"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'dm'
    and owner = auth.uid()
    and public.dm_is_member(public.dm_path_conversation(name))
  );

  drop policy if exists "Senders remove their own files" on storage.objects;
  create policy "Senders remove their own files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'dm' and owner = auth.uid());

exception when others then
  raise notice 'Attachments are not set up: %. Messages still work; photos '
    'and files will not until the dm bucket and its policies exist. '
    'Create the bucket in Storage and re-run this section.', sqlerrm;
end $$;


-- ------------------------------------------------------------
-- 8. Check it
--
--   -- should list messages and conversation_participants
--   select tablename from pg_publication_tables
--   where pubname = 'supabase_realtime' and schemaname = 'public';
--
--   -- signed in as a driver, this should answer without error
--   select * from public.dm_threads();
--   select * from public.dm_directory();
--
--   -- and drivers.avatar should be there
--   select column_name from information_schema.columns
--   where table_schema = 'public' and table_name = 'drivers'
--     and column_name = 'avatar';
-- ------------------------------------------------------------
