-- ============================================================
-- GAMING NATION — live driver positions
--
-- Run this in Supabase -> SQL Editor. Idempotent, like setup.sql:
-- safe on a fresh project and safe to re-run. Nothing here drops
-- data.
--
-- What this is for: driver-dashboard.html inserts every GPS fix
-- into public.driver_locations and subscribes to postgres_changes
-- on public.drivers. Neither of those appeared anywhere in
-- setup.sql or the earlier migrations.
--
-- IMPORTANT — the live project (sfzeauvkguywidrqjntk) was checked
-- on 2026-09-04 and already had both:
--
--   * public.driver_locations exists, with driver_id (bigint),
--     latitude, longitude, speed, heading and updated_at. It does
--     NOT have created_at, which section 1 adds.
--   * drivers, driver_locations and applications are all already
--     in the supabase_realtime publication.
--
-- So on that project this file is close to a no-op, and it is
-- written to stay that way: it reconciles rather than assumes.
-- What it is really for is the schema files describing the
-- database again — setup.sql knew about none of this, so a fresh
-- project built from the repo came up without the table the
-- driver terminal writes to.
--
-- Both failure modes are silent from the browser, which is the
-- worst way for them to fail: a missing table comes back as a
-- PostgREST error the page logs and carries on from, and an
-- unpublished table reports SUBSCRIBED and then stays quiet for
-- ever.
--
-- The key: driver_locations.driver_id is drivers.id (bigint), NOT
-- drivers.driver_code. applications.driver_id is the text code —
-- the same column name means different things on the two tables,
-- which is exactly why this one is spelled out here.
-- ============================================================


-- ------------------------------------------------------------
-- 1. The table
-- ------------------------------------------------------------

create table if not exists public.driver_locations (
  id          bigint generated by default as identity primary key,
  driver_id   bigint not null references public.drivers(id) on delete cascade,
  latitude    double precision not null,
  longitude   double precision not null,
  speed       double precision,
  heading     double precision,
  updated_at  timestamptz not null default now(),
  created_at  timestamptz not null default now()
);

-- create table if not exists does nothing to a table that is already
-- there, and the live one predates this file and has no created_at.
-- Every other table in setup.sql carries one, so it is added rather
-- than the convention being quietly dropped for this one.
alter table public.driver_locations
  add column if not exists created_at timestamptz not null default now();

-- "Where is each driver now" is the only question anyone asks of
-- this table, and it is asked on every render of the fleet map.
-- Newest-first per driver is therefore the index that matters.
create index if not exists driver_locations_driver_idx
  on public.driver_locations (driver_id, updated_at desc);

-- A position is worthless a day later, but the rows still cost
-- money. This index is what makes the prune below cheap.
create index if not exists driver_locations_updated_idx
  on public.driver_locations (updated_at);


-- ------------------------------------------------------------
-- 2. Row level security
--
-- Same shape as drivers: a driver owns their own rows, staff see
-- the fleet. Ownership has to be resolved through drivers, because
-- the location row carries a bigint driver id and auth carries a
-- uuid — there is no column here to compare against auth.uid().
-- ------------------------------------------------------------

alter table public.driver_locations enable row level security;

drop policy if exists "Drivers can record their own position" on public.driver_locations;
create policy "Drivers can record their own position"
on public.driver_locations for insert to authenticated
with check (
  driver_id in (select id from public.drivers where auth_user_id = auth.uid())
);

drop policy if exists "Drivers can read their own positions" on public.driver_locations;
create policy "Drivers can read their own positions"
on public.driver_locations for select to authenticated
using (
  driver_id in (select id from public.drivers where auth_user_id = auth.uid())
);

-- Without this the dispatcher's fleet map is empty: staff would see
-- only their own truck.
drop policy if exists "Staff can read every position" on public.driver_locations;
create policy "Staff can read every position"
on public.driver_locations for select to authenticated
using (public.is_staff());


-- ------------------------------------------------------------
-- 3. Realtime
--
-- payload.new already carries every column on an INSERT or UPDATE
-- whatever the replica identity is, so the dashboard's filter on
-- auth_user_id works without this. What the default identity does
-- not give you is payload.old beyond the primary key, which is
-- what a DELETE payload and any filter over old values need. Set
-- here so that stays available rather than being discovered
-- missing later.
-- ------------------------------------------------------------

alter table public.drivers           replica identity full;
alter table public.driver_locations  replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    create publication supabase_realtime;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'drivers'
  ) then
    alter publication supabase_realtime add table public.drivers;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'driver_locations'
  ) then
    alter publication supabase_realtime add table public.driver_locations;
  end if;
end $$;


-- ------------------------------------------------------------
-- 4. Keeping the table small
--
-- A driver on shift writes a row a second. Call it 86k rows a day
-- each, none of which is interesting once the next one lands. This
-- keeps a day of history for replaying a run and drops the rest.
-- Call it from a scheduled job, or by hand:
--
--   select public.prune_driver_locations();
-- ------------------------------------------------------------

create or replace function public.prune_driver_locations(keep interval default '24 hours')
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  removed bigint;
begin
  delete from public.driver_locations
  where updated_at < now() - keep;

  get diagnostics removed = row_count;
  return removed;
end $$;


-- ------------------------------------------------------------
-- 5. Check it
--
--   select count(*) from public.driver_locations;
--
--   -- should list drivers and driver_locations
--   select tablename from pg_publication_tables
--   where pubname = 'supabase_realtime' and schemaname = 'public';
-- ------------------------------------------------------------
